import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import {
  LucideAngularModule,
  // Finance
  Wallet,
  CreditCard,
  Banknote,
  Coins,
  DollarSign,
  PiggyBank,
  Receipt,
  Percent,
  // Trends / Charts
  TrendingUp,
  TrendingDown,
  BarChart2,
  BarChart3,
  PieChart,
  LineChart,
  ChartBar,
  // Goals / Status
  Target,
  Trophy,
  Star,
  Rocket,
  Key,
  Shield,
  Flame,
  Circle,
  // Life & Assets
  Home,
  Car,
  Plane,
  GraduationCap,
  Gem,
  Baby,
  HeartPulse,
  Umbrella,
  Globe,
  MapPin,
  // Tech & Media
  Laptop,
  Smartphone,
  Music,
  Clapperboard,
  Gamepad2,
  Film,
  Database,
  // Shopping & Food
  Utensils,
  Coffee,
  ShoppingCart,
  ShoppingBag,
  // Objects
  Tag,
  Book,
  Package,
  Sprout,
  Briefcase,
  Gift,
  Dumbbell,
  Wrench,
  FolderOpen,
  FileText,
  Calculator,
  Building,
  Building2,
  Landmark,
  // UI icons
  Search,
  ChevronDown,
  ChevronUp,
  MoreHorizontal,
  ArrowUp,
  ArrowDown,
  ArrowRight,
  RefreshCw,
  Check,
  CheckCircle,
  CheckCircle2,
  AlertTriangle,
  AlertCircle,
  X,
  Plus,
  Pencil,
  Trash2,
  Info,
  Loader2,
  Pause,
  Eye,
  EyeOff,
  Map,
  Newspaper,
  Zap,
  Download,
  // Layout / Navigation
  LayoutGrid,
  LayoutDashboard,
  // Settings / System
  Settings,
  Bell,
  User,
  Mail,
  Lock,
  Moon,
  Sun,
  UserPlus,
  Lightbulb
} from 'lucide-angular';
import { AbsPipe } from './pipes/abs.pipe';
import { AppIconComponent } from './components/app-icon/app-icon.component';
import { AppDropdownComponent } from './components/app-dropdown/app-dropdown.component';
import { IconPickerComponent } from './components/icon-picker/icon-picker.component';
import { ColorPickerComponent } from './components/color-picker/color-picker.component';

@NgModule({
  declarations: [
    AbsPipe,
    AppIconComponent,
    AppDropdownComponent,
    IconPickerComponent,
    ColorPickerComponent
  ],
  imports: [
    CommonModule,
    RouterModule,
    FormsModule,
    ReactiveFormsModule,
    LucideAngularModule.pick({
      Wallet,
      CreditCard,
      Banknote,
      Coins,
      DollarSign,
      PiggyBank,
      Receipt,
      Percent,
      TrendingUp,
      TrendingDown,
      BarChart2,
      BarChart3,
      PieChart,
      LineChart,
      ChartBar,
      Target,
      Trophy,
      Star,
      Rocket,
      Key,
      Shield,
      Flame,
      Circle,
      Home,
      Car,
      Plane,
      GraduationCap,
      Gem,
      Baby,
      HeartPulse,
      Umbrella,
      Globe,
      MapPin,
      Laptop,
      Smartphone,
      Music,
      Clapperboard,
      Gamepad2,
      Film,
      Database,
      Utensils,
      Coffee,
      ShoppingCart,
      ShoppingBag,
      Tag,
      Book,
      Package,
      Sprout,
      Briefcase,
      Gift,
      Dumbbell,
      Wrench,
      FolderOpen,
      FileText,
      Calculator,
      Building,
      Building2,
      Landmark,
      Search,
      ChevronDown,
      ChevronUp,
      MoreHorizontal,
      ArrowUp,
      ArrowDown,
      ArrowRight,
      RefreshCw,
      Check,
      CheckCircle,
      CheckCircle2,
      AlertTriangle,
      AlertCircle,
      X,
      Plus,
      Pencil,
      Trash2,
      Info,
      Loader2,
      Pause,
      Eye,
      EyeOff,
      Map,
      Newspaper,
      Zap,
      Download,
      LayoutGrid,
      LayoutDashboard,
      Settings,
      Bell,
      User,
      Mail,
      Lock,
      Moon,
      Sun,
      UserPlus,
      Lightbulb
    })
  ],
  exports: [
    CommonModule,
    RouterModule,
    FormsModule,
    ReactiveFormsModule,
    AbsPipe,
    AppIconComponent,
    AppDropdownComponent,
    IconPickerComponent,
    ColorPickerComponent,
    LucideAngularModule
  ]
})
export class SharedModule {}
