import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import {
  LucideAngularModule,
  Wallet,
  Home,
  Tag,
  Book,
  Bell,
  Settings,
  LayoutGrid,
  ChartBar,
  BarChart2,
  TrendingUp,
  CreditCard,
  PiggyBank,
  Target,
  Circle,
  Car,
  Utensils,
  ShoppingCart,
  Heart,
  GraduationCap,
  Plane,
  Film,
  Lightbulb,
  Smartphone,
  DollarSign,
  Briefcase,
  Gift,
  Dumbbell,
  Wrench,
  Gamepad2,
  Coffee,
  Sprout,
  Package,
  ArrowUp,
  ArrowDown,
  RefreshCw,
  MoreHorizontal,
  PieChart,
  FolderOpen,
  CheckCircle,
  AlertTriangle,
  Banknote,
  Eye,
  EyeOff,
  Map,
  Newspaper,
  Rocket,
  Building2,
  Landmark,
  FileText,
  Calculator
} from 'lucide-angular';
import { AbsPipe } from './pipes/abs.pipe';
import { AppIconComponent } from './components/app-icon/app-icon.component';
import { AppDropdownComponent } from './components/app-dropdown/app-dropdown.component';

@NgModule({
  declarations: [AbsPipe, AppIconComponent, AppDropdownComponent],
  imports: [
    CommonModule,
    RouterModule,
    LucideAngularModule.pick({
      Wallet,
      Home,
      Tag,
      Book,
      Bell,
      Settings,
      LayoutGrid,
      ChartBar,
      BarChart2,
      TrendingUp,
      CreditCard,
      PiggyBank,
      Target,
      Circle,
      Car,
      Utensils,
      ShoppingCart,
      Heart,
      GraduationCap,
      Plane,
      Film,
      Lightbulb,
      Smartphone,
      DollarSign,
      Briefcase,
      Gift,
      Dumbbell,
      Wrench,
      Gamepad2,
      Coffee,
      Sprout,
      Package,
      ArrowUp,
      ArrowDown,
      RefreshCw,
      MoreHorizontal,
      PieChart,
      FolderOpen,
      CheckCircle,
      AlertTriangle,
      Banknote,
      Eye,
      EyeOff,
      Map,
      Newspaper,
      Rocket,
      Building2,
      Landmark,
      FileText,
      Calculator
    })
  ],
  exports: [
    CommonModule,
    RouterModule,
    AbsPipe,
    AppIconComponent,
    AppDropdownComponent,
    LucideAngularModule
  ]
})
export class SharedModule {}